"""removendo a coluna de imagens

Revision ID: 0514751a9288
Revises: e7ee8e8e2a2b
Create Date: 2025-02-25 00:32:08.804208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0514751a9288'
down_revision = 'e7ee8e8e2a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
