"""Adicionando coluna mensagem

Revision ID: 79372abe8fef
Revises: 1ee48ce89466
Create Date: 2025-02-18 03:35:41.562873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79372abe8fef'
down_revision = '1ee48ce89466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('Mensagens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mensagens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('mensagens')
    # ### end Alembic commands ###
